# permissions for end users to edit databases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: database-editor-role
rules:
- apiGroups:
  - expense-app.majorov.biz
  resources:
  - databases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - expense-app.majorov.biz
  resources:
  - databases/status
  verbs:
  - get
